apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp
  namespace: myapp
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/myapp
      sourceRef:
        kind: GitRepository
        name: myapp-env
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: myapp-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3